# Generated by Django 5.1.1 on 2024-10-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_blog_published_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="published",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="published_date",
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
