# Generated by Django 5.1.1 on 2024-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_blog_published_remove_blog_published_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
