# Generated by Django 5.0.6 on 2024-06-14 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0001_initial"),
        ("products", "0002_alter_category_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="order_line_item",
            new_name="OrderLineItem",
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
