# Generated by Django 5.0.6 on 2024-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checkout", "0003_order_user_profile_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_reference",
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
