# Generated by Django 5.0.6 on 2024-10-04 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_carbon_fp_total_order_carbon_saved_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carbon_fp_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='carbon_saved_total',
        ),
    ]
