# Generated by Django 5.0.6 on 2024-10-04 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_order_carbon_fp_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_size',
            new_name='product_colour',
        ),
    ]
