# Generated by Django 5.0.6 on 2024-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_product_size_orderlineitem_product_colour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='product_colour',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
